# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    # Register 'protocols' module with dependencies
    module = bld.create_ns3_module('sag-transport', ['core', 'internet', 'applications', 'point-to-point', 'traffic-control'])

    # Source files
    module.source = [    	
        'helper/tcp-optimizer.cc',
        'helper/quic-optimizer.cc',
        'helper/scps-tp-optimizer.cc',
        ]

    # Header files
    headers = bld(features='ns3header')
    headers.module = 'sag-transport'
    headers.source = [
        'helper/tcp-optimizer.h',
        'helper/quic-optimizer.h',
        'helper/scps-tp-optimizer.h',
        ]

    # Tests
    # module_test = bld.create_ns3_module_test_library('protocols')
    # module_test.source = [
    #   'test/basic-sim-test-suite.cc',
    #    ]

    # Main
    #bld.recurse('main')

    # Examples
    #if bld.env.ENABLE_EXAMPLES:
    #    bld.recurse('examples')

    # For now, no Python bindings are generated
    # bld.ns3_python_bindings()
